apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservices-prod
spec:
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
    protocol: TCP
  type: NodePort
