apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: microservices-staging
  labels:
    app: auth-api
    environment: staging
spec:
  selector:
    app: auth-api
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
