apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: microservices-prod
spec:
  selector:
    app: log-message-processor
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP


