apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: microservices-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: ${REGISTRY}/log-message-processor:${IMAGE_TAG}
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_HOST }
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_PORT }
            - name: REDIS_CHANNEL
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_CHANNEL }
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef: { name: micro-config, key: ZIPKIN_URL }
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"


