kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30083
    hostPort: 8083
    listenAddress: "0.0.0.0"
    protocol: TCP