apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: microservices-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: microservices-staging
spec:
  selector:
    app: redis-cache
  ports:
  - port: 6379
    targetPort: 6379
