apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: microservices-prod
  labels:
    app: auth-api
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
        environment: production
    spec:
      containers:
      - name: auth-api
        image: ${REGISTRY}/auth-api:${IMAGE_TAG}
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_API_PORT
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: AUTH_API_PORT
        - name: USERS_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: USERS_API_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: JWT_SECRET
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: ZIPKIN_URL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
