apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: microservices-prod
  labels:
    app: auth-api
    environment: production
spec:
  selector:
    app: auth-api
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
  type: NodePort
