apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservices-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: ${REGISTRY}/todos-api:${IMAGE_TAG}
          ports:
            - containerPort: 8082
          env:
            - name: TODO_API_PORT
              valueFrom:
                configMapKeyRef: { name: micro-config, key: TODOS_API_PORT }
            - name: USERS_API_ADDRESS
              valueFrom:
                configMapKeyRef: { name: micro-config, key: USERS_API_URL }
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef: { name: micro-config, key: ZIPKIN_URL }
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_HOST }
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_PORT }
            - name: REDIS_CHANNEL
              valueFrom:
                configMapKeyRef: { name: micro-config, key: REDIS_QUEUE_CHANNEL }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: micro-secrets, key: JWT_SECRET }
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


