apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todos-api
  namespace: microservices-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todos-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50


