apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: microservices-prod
spec:
  selector:
    app: todos-api
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    nodePort: 30082
  type: NodePort
