apiVersion: v1
kind: Secret
metadata:
  name: micro-secrets
  namespace: micro
type: Opaque
data:
  # JWT Secret (base64 encoded)
  # Para generar: echo -n "myfancysecret" | base64
  JWT_SECRET: bXlmYW5jeXNlY3JldA==
